name: jubilant
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-99.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Inter
      fonts:
        - asset: font/Inter-Regular.ttf
        - asset: font/Inter-Black.ttf
        - asset: font/Inter-Bold.ttf
        - asset: font/Inter-ExtraBold.ttf
        - asset: font/Inter-ExtraLight.ttf
        - asset: font/Inter-Light.ttf
        - asset: font/Inter-Medium.ttf
        - asset: font/Inter-Regular.ttf
        - asset: font/Inter-SemiBold.ttf
        - asset: font/Inter-Thin.ttf
